stages:
  -   stage: Build_Test
      displayName: Build and Test artifacts
      jobs:
        -   job: Build_Test
            pool:
              vmImage: 'ubuntu-latest'
            steps:
              - task: NodeTool@0
                inputs:
                  versionSpec: '10.x'
                displayName: 'Install Node.js'

              - task: Bash@3
                inputs:
                    targetType: 'inline'
                    script: |
                      docker pull laymui/react-app-typescript:0.0.1.RELEASE
                      docker run -d -p 3000:3000 laymui/react-app-typescript:0.0.1.RELEASE
                      displayName: 'pull docker image and run container to start server'
 
                      npm install
                      npm test
                      displayName: 'npm install and test'
 
              - task: CopyFiles@2
                inputs:
                  sourceFolder: $(Build.SourcesDirectory)
                  contents: |
                    **
                  TargetFolder: $(Build.ArtifactStagingDirectory)
              - task: PublishPipelineArtifact@1
                inputs:
                  targetPath: $(Build.ArtifactStagingDirectory)
                  artifactName: test-source-folder
 
        - job: create_test_reports_web
          displayName: Create web with test reports
          pool:
            vmImage: 'ubuntu-latest'
            dependsOn: Build_Test
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'test-source-folder'
                  targetPath: '$(Pipeline.Workspace)'
      
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'Azure subscription 1 - demo'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az webapp delete -n react-app-todo -g demo'
                 
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'Azure subscription 1 - demo'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az webapp up -n react-app-todo -g demo -l southeastasia -p demo --html'
                  workingDirectory: '$(Pipeline.Workspace)/target/site/serenity'
          