resources: 
  pipelines:
  - pipeline: 1
    project: mui_ume
    source: LayMui.react-app-typescript
    branch: master  
    trigger:  
      enabled: true
 
pool:
  vmImage: 'ubuntu-latest'
 
- script: |
    npm install
    npm test
  displayName: 'npm install and test'
 
