pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker pull laymui/react-app-typescript:0.0.1.RELEASE
      docker run -d -p 3000:3000 laymui/react-app-typescript:0.0.1.RELEASE
   
- script: |
    npm install
    npm test
  displayName: 'npm install and test'
 
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: |
      target/site/serenity/**
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactName: target-folder
 
