resources: 
  pipelines:
  - pipeline: 1
    project: mui_ume
    source: LayMui.react-app-typescript
    branch: master  
    trigger:  
      enabled: true
 
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    echo "HELLO WORLD"
  displayName: 'npm install and test'
 

 
